### PR TITLE
Add New Endpoints and SDK Header

### PR DESCRIPTION
**Pull request by CrshOverride**

### CODE REVIEW

**Review by karnowski — CHANGES_REQUESTED** [review]
This is a great start!  However, there's a few other things we should consider.

- [x] We should add an `instant_counts` method to the `CreativeMap` object too.  (That's the Ruby SDK object for "ad".)
- [x] There's no way to make a bulk instant count call.  Not sure where we'd hang that?  It's important, though, as it's the most used instant count call and one of the most used calls overall in our mgmt API.
- [ ] We should either 1) add a `list_flights` method on the `Adzerk::Campaign` object, or 2) be like the JS Mgmt SDK and add a `list_for_campaign` method on a new `Adzerk::Flight` object.
- [ ] Is there any way to add a default `pageSize` to `list` endpoints like we did on the JS Mgmt SDK via Swagger?
- [ ] Why in `client.rb` does it mostly use `SDK_HEADER_NAME` but on line 74 it uses `:X-Adzerk_Sdk_Version`?  Looks like line 86 is inconsistent too, it uses a string (which is probably preferred given it's a header name?) rather than a symbol.
- [ ] In the `client` object, the `flights` object is NOT an instance of `Adzerk::Flight`. That's a bug right?  (An old one, but a bug, right?)

**Comment by karnowski** [comment]
Let me add another:

- Let's create a `client.ad` alias for `client.creative_map` because that's crazy town.  Everyone nowadays expects `ad`, right?

**Comment by karnowski** [comment]
- Should we create a `client.instant_counts` to hang the `bulk` method on?

**Comment by CrshOverride** [comment]
> This is a great start! However, there's a few other things we should consider.
> 
> * [x]  We should add an `instant_counts` method to the `CreativeMap` object too.  (That's the Ruby SDK object for "ad".)
> * [x]  There's no way to make a bulk instant count call.  Not sure where we'd hang that?  It's important, though, as it's the most used instant count call and one of the most used calls overall in our mgmt API.
> * [x]  We should either 1) add a `list_flights` method on the `Adzerk::Campaign` object, or 2) be like the JS Mgmt SDK and add a `list_for_campaign` method on a new `Adzerk::Flight` object.
> * [ ]  Is there any way to add a default `pageSize` to `list` endpoints like we did on the JS Mgmt SDK via Swagger?
> * [ ]  Why in `client.rb` does it mostly use `SDK_HEADER_NAME` but on line 74 it uses `:X-Adzerk_Sdk_Version`?  Looks like line 86 is inconsistent too, it uses a string (which is probably preferred given it's a header name?) rather than a symbol.
> * [x]  In the `client` object, the `flights` object is NOT an instance of `Adzerk::Flight`. That's a bug right?  (An old one, but a bug, right?)

@karnowski I've addressed everything that is checked off in the list as well as the other two comments. There's a separate issue for paging since that's not currently supported at all. As for the header differences, I was following the existing pattern rather than attempt something and risk breaking existing functionality.

**Comment by CrshOverride** [comment]
@karnowski And, as far as the failing test is concerned, that is new behavior in the API. I'm still working with the team internally to figure out if the change is a bug or was expected behavior.

**Review by karnowski — APPROVED** [review]
:+1: Looks good to me!

**Pull request merged**
